//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-updateQuoteById-DMOPS_ID_quote_management___EN_k3pc1nknge__updateQuoteById
import { updateQuoteById as DMOPS_ID_quote_management___EN_k3pc1nknge__updateQuoteById } from './dm-services/quote_management/quote/updateQuoteById';
//CORE_REFERENCE_IMPORT-updateAllQuotes-DMOPS_ID_quote_management___EN_k3pc1nknge__updateAllQuotes
import { updateAllQuotes as DMOPS_ID_quote_management___EN_k3pc1nknge__updateAllQuotes } from './dm-services/quote_management/quote/updateAllQuotes';
//CORE_REFERENCE_IMPORT-findQuoteById-DMOPS_ID_quote_management___EN_k3pc1nknge__findQuoteById
import { findQuoteById as DMOPS_ID_quote_management___EN_k3pc1nknge__findQuoteById } from './dm-services/quote_management/quote/findQuoteById';
//CORE_REFERENCE_IMPORT-findAllQuotes-DMOPS_ID_quote_management___EN_k3pc1nknge__findAllQuotes
import { findAllQuotes as DMOPS_ID_quote_management___EN_k3pc1nknge__findAllQuotes } from './dm-services/quote_management/quote/findAllQuotes';
//CORE_REFERENCE_IMPORT-deleteQuoteById-DMOPS_ID_quote_management___EN_k3pc1nknge__deleteQuoteById
import { deleteQuoteById as DMOPS_ID_quote_management___EN_k3pc1nknge__deleteQuoteById } from './dm-services/quote_management/quote/deleteQuoteById';
//CORE_REFERENCE_IMPORT-deleteAllQuotes-DMOPS_ID_quote_management___EN_k3pc1nknge__deleteAllQuotes
import { deleteAllQuotes as DMOPS_ID_quote_management___EN_k3pc1nknge__deleteAllQuotes } from './dm-services/quote_management/quote/deleteAllQuotes';
//CORE_REFERENCE_IMPORT-createAllQuote-DMOPS_ID_quote_management___EN_k3pc1nknge__createAllQuote
import { createAllQuote as DMOPS_ID_quote_management___EN_k3pc1nknge__createAllQuote } from './dm-services/quote_management/quote/createAllQuote';
//CORE_REFERENCE_IMPORT-createQuote-DMOPS_ID_quote_management___EN_k3pc1nknge__createQuote
import { createQuote as DMOPS_ID_quote_management___EN_k3pc1nknge__createQuote } from './dm-services/quote_management/quote/createQuote';

export const DmRoutes = [
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateQuoteById-DMOPS_ID_quote_management___EN_k3pc1nknge__updateQuoteById
  DMOPS_ID_quote_management___EN_k3pc1nknge__updateQuoteById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateAllQuotes-DMOPS_ID_quote_management___EN_k3pc1nknge__updateAllQuotes
  DMOPS_ID_quote_management___EN_k3pc1nknge__updateAllQuotes,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findQuoteById-DMOPS_ID_quote_management___EN_k3pc1nknge__findQuoteById
  DMOPS_ID_quote_management___EN_k3pc1nknge__findQuoteById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findAllQuotes-DMOPS_ID_quote_management___EN_k3pc1nknge__findAllQuotes
  DMOPS_ID_quote_management___EN_k3pc1nknge__findAllQuotes,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteQuoteById-DMOPS_ID_quote_management___EN_k3pc1nknge__deleteQuoteById
  DMOPS_ID_quote_management___EN_k3pc1nknge__deleteQuoteById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-deleteAllQuotes-DMOPS_ID_quote_management___EN_k3pc1nknge__deleteAllQuotes
  DMOPS_ID_quote_management___EN_k3pc1nknge__deleteAllQuotes,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createAllQuote-DMOPS_ID_quote_management___EN_k3pc1nknge__createAllQuote
  DMOPS_ID_quote_management___EN_k3pc1nknge__createAllQuote,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createQuote-DMOPS_ID_quote_management___EN_k3pc1nknge__createQuote
  DMOPS_ID_quote_management___EN_k3pc1nknge__createQuote,
];
