//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-updateOtpRegistryById-DMOPS_ID_communication___EN_xmu5gi50dz__updateOtpRegistryById
import { updateOtpRegistryById as DMOPS_ID_communication___EN_xmu5gi50dz__updateOtpRegistryById } from './dm-services/communication/otp_registry/updateOtpRegistryById';
//CORE_REFERENCE_IMPORT-updateAllOtpRegistrys-DMOPS_ID_communication___EN_xmu5gi50dz__updateAllOtpRegistrys
import { updateAllOtpRegistrys as DMOPS_ID_communication___EN_xmu5gi50dz__updateAllOtpRegistrys } from './dm-services/communication/otp_registry/updateAllOtpRegistrys';
//CORE_REFERENCE_IMPORT-findOtpRegistryById-DMOPS_ID_communication___EN_xmu5gi50dz__findOtpRegistryById
import { findOtpRegistryById as DMOPS_ID_communication___EN_xmu5gi50dz__findOtpRegistryById } from './dm-services/communication/otp_registry/findOtpRegistryById';
//CORE_REFERENCE_IMPORT-createOtpRegistry-DMOPS_ID_communication___EN_xmu5gi50dz__createOtpRegistry
import { createOtpRegistry as DMOPS_ID_communication___EN_xmu5gi50dz__createOtpRegistry } from './dm-services/communication/otp_registry/createOtpRegistry';

export const DmRoutes = [
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateOtpRegistryById-DMOPS_ID_communication___EN_xmu5gi50dz__updateOtpRegistryById
  DMOPS_ID_communication___EN_xmu5gi50dz__updateOtpRegistryById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateAllOtpRegistrys-DMOPS_ID_communication___EN_xmu5gi50dz__updateAllOtpRegistrys
  DMOPS_ID_communication___EN_xmu5gi50dz__updateAllOtpRegistrys,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-findOtpRegistryById-DMOPS_ID_communication___EN_xmu5gi50dz__findOtpRegistryById
  DMOPS_ID_communication___EN_xmu5gi50dz__findOtpRegistryById,
  //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createOtpRegistry-DMOPS_ID_communication___EN_xmu5gi50dz__createOtpRegistry
  DMOPS_ID_communication___EN_xmu5gi50dz__createOtpRegistry,
];
