//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-ping-SSD_SERVICE_ID_sd_iabM9jEvbPWhOT70
import { ping as SSD_SERVICE_ID_sd_iabM9jEvbPWhOT70 } from './sd-services/common/ping';
//CORE_REFERENCE_IMPORT-flows-SSD_SERVICE_ID_sd_1baOHKnauKP8XEGS
import { flows as SSD_SERVICE_ID_sd_1baOHKnauKP8XEGS } from './sd-services/master_data/flows';
//CORE_REFERENCE_IMPORT-flows-SSD_SERVICE_ID_sd_Mh9vsV05OPUVdmq9
import { flows as SSD_SERVICE_ID_sd_Mh9vsV05OPUVdmq9 } from './sd-services/strapi/flows';
//CORE_REFERENCE_IMPORT-flows-SSD_SERVICE_ID_sd_GP8ZqpvWCN4F8G1B
import { flows as SSD_SERVICE_ID_sd_GP8ZqpvWCN4F8G1B } from './sd-services/utils/flows';
//CORE_REFERENCE_IMPORT-apis-SSD_SERVICE_ID_sd_gZ6q91i7V8n4YhLT
import { apis as SSD_SERVICE_ID_sd_gZ6q91i7V8n4YhLT } from './sd-services/document/apis';
//CORE_REFERENCE_IMPORT-flows-SSD_SERVICE_ID_sd_CipFh1pFceESOsZK
import { flows as SSD_SERVICE_ID_sd_CipFh1pFceESOsZK } from './sd-services/document/flows';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-ping-SSD_SERVICE_ID_sd_iabM9jEvbPWhOT70
SSD_SERVICE_ID_sd_iabM9jEvbPWhOT70,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-flows-SSD_SERVICE_ID_sd_1baOHKnauKP8XEGS
SSD_SERVICE_ID_sd_1baOHKnauKP8XEGS,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-flows-SSD_SERVICE_ID_sd_Mh9vsV05OPUVdmq9
SSD_SERVICE_ID_sd_Mh9vsV05OPUVdmq9,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-flows-SSD_SERVICE_ID_sd_GP8ZqpvWCN4F8G1B
SSD_SERVICE_ID_sd_GP8ZqpvWCN4F8G1B,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-apis-SSD_SERVICE_ID_sd_gZ6q91i7V8n4YhLT
SSD_SERVICE_ID_sd_gZ6q91i7V8n4YhLT,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-flows-SSD_SERVICE_ID_sd_CipFh1pFceESOsZK
SSD_SERVICE_ID_sd_CipFh1pFceESOsZK,
];
